apiVersion: recert5.uberscott.com/v1
kind: RecertSSLReverseProxy
metadata:
  name: {{ .Values.Name }}
spec:
  {{ if .Values.LoadBalancerIP }} 
  loadBalancerIP: {{ .Values.LoadBalancerIP }} 
  {{ end }}
  pass: "http://{{ .Values.Pass }}:80"
  replicas: 1
