# permissions for end users to edit recertsslreverseproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recertsslreverseproxy-editor-role
rules:
- apiGroups:
  - recert5.uberscott.com
  resources:
  - recertsslreverseproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - recert5.uberscott.com
  resources:
  - recertsslreverseproxies/status
  verbs:
  - get
