# permissions for end users to edit recerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recert-editor-role
rules:
- apiGroups:
  - recert5.uberscott.com
  resources:
  - recerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - recert5.uberscott.com
  resources:
  - recerts/status
  verbs:
  - get
