# permissions for end users to view recerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recert-viewer-role
rules:
- apiGroups:
  - mightydevco.mightydevco.com
  resources:
  - recerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mightydevco.mightydevco.com
  resources:
  - recerts/status
  verbs:
  - get
