apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.9.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: recert5.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Renews Let's Encrypt SSL certs automatically
  displayName: Recert5
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ssl
  - tls
  - proxy
  - reverse proxy
  - https
  links:
  - name: Recert5
    url: https://recert5.domain
  maturity: alpha
  provider:
    name: uberscott
    url: uberscott.com
  version: 0.0.1
